-- Legacy prototype migration intentionally left empty.
-- It referenced feed_posts and telemetry_sessions tables that never existed,
-- and its unused cart/order model has been superseded by provider-backed parts search.
